// import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_component/Header";
import Footer from "./_component/Footer";
import { Toaster } from "../components/ui/sonner"

// const outfit = Outfit({

//   subsets: ["latin"],
// });

export const metadata = {
  title: "Appointment Doctor",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/favicon.ico", 
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body
        className={`${outfit.className} antialiased`}
      > */}
      <body className="font-sans antialiased">
        <div className="md:px-20">
        <Header/>
       
       
        {children}
        <Toaster />
       <Footer/>
        </div>
      </body>
    </html>
  );
}
